'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property LastPlaylistFile() As String
        Get
            Return CType(Me("LastPlaylistFile"),String)
        End Get
        Set
            Me("LastPlaylistFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Default")>  _
    Public Property EnvironmentName() As String
        Get
            Return CType(Me("EnvironmentName"),String)
        End Get
        Set
            Me("EnvironmentName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property CurrentSkin() As String
        Get
            Return CType(Me("CurrentSkin"),String)
        End Get
        Set
            Me("CurrentSkin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SavePlaylistOnChange() As Boolean
        Get
            Return CType(Me("SavePlaylistOnChange"),Boolean)
        End Get
        Set
            Me("SavePlaylistOnChange") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
    Public Property PlaybackTick() As Integer
        Get
            Return CType(Me("PlaybackTick"),Integer)
        End Get
        Set
            Me("PlaybackTick") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
    Public Property SaveTick() As Integer
        Get
            Return CType(Me("SaveTick"),Integer)
        End Get
        Set
            Me("SaveTick") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ActiveProducer")>  _
    Public Property DefaultFollowAction() As Global.NextPlayer.FollowActionTypes
        Get
            Return CType(Me("DefaultFollowAction"),Global.NextPlayer.FollowActionTypes)
        End Get
        Set
            Me("DefaultFollowAction") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
    Public Property PowerPointUpdateInterval() As Integer
        Get
            Return CType(Me("PowerPointUpdateInterval"),Integer)
        End Get
        Set
            Me("PowerPointUpdateInterval") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property UseUpdateTimer() As Boolean
        Get
            Return CType(Me("UseUpdateTimer"),Boolean)
        End Get
        Set
            Me("UseUpdateTimer") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property VoiceCommands() As Global.Common.VoiceCommandConfigItemCollection
        Get
            Return CType(Me("VoiceCommands"),Global.Common.VoiceCommandConfigItemCollection)
        End Get
        Set
            Me("VoiceCommands") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property LastExportDir() As String
        Get
            Return CType(Me("LastExportDir"),String)
        End Get
        Set
            Me("LastExportDir") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property SettingsWindowLeft() As Double
        Get
            Return CType(Me("SettingsWindowLeft"),Double)
        End Get
        Set
            Me("SettingsWindowLeft") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property SettingsWindowTop() As Double
        Get
            Return CType(Me("SettingsWindowTop"),Double)
        End Get
        Set
            Me("SettingsWindowTop") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("450")>  _
    Public Property SettingsWindowWidth() As Double
        Get
            Return CType(Me("SettingsWindowWidth"),Double)
        End Get
        Set
            Me("SettingsWindowWidth") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
    Public Property SettingsWindowHeight() As Double
        Get
            Return CType(Me("SettingsWindowHeight"),Double)
        End Get
        Set
            Me("SettingsWindowHeight") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Upgraded() As Boolean
        Get
            Return CType(Me("Upgraded"),Boolean)
        End Get
        Set
            Me("Upgraded") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PrintWindowLeft() As Double
        Get
            Return CType(Me("PrintWindowLeft"),Double)
        End Get
        Set
            Me("PrintWindowLeft") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PrintWindowTop() As Double
        Get
            Return CType(Me("PrintWindowTop"),Double)
        End Get
        Set
            Me("PrintWindowTop") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("600")>  _
    Public Property PrintWindowWidth() As Double
        Get
            Return CType(Me("PrintWindowWidth"),Double)
        End Get
        Set
            Me("PrintWindowWidth") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("700")>  _
    Public Property PrintWindowHeight() As Double
        Get
            Return CType(Me("PrintWindowHeight"),Double)
        End Get
        Set
            Me("PrintWindowHeight") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property AudioPositionWindowLeft() As Double
        Get
            Return CType(Me("AudioPositionWindowLeft"),Double)
        End Get
        Set
            Me("AudioPositionWindowLeft") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property AudioPositionWindowTop() As Double
        Get
            Return CType(Me("AudioPositionWindowTop"),Double)
        End Get
        Set
            Me("AudioPositionWindowTop") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
    Public Property AudioPositionWindowWidth() As Double
        Get
            Return CType(Me("AudioPositionWindowWidth"),Double)
        End Get
        Set
            Me("AudioPositionWindowWidth") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("550")>  _
    Public Property AudioPositionWindowHeight() As Double
        Get
            Return CType(Me("AudioPositionWindowHeight"),Double)
        End Get
        Set
            Me("AudioPositionWindowHeight") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property AboutWindowLeft() As Double
        Get
            Return CType(Me("AboutWindowLeft"),Double)
        End Get
        Set
            Me("AboutWindowLeft") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property AboutWindowTop() As Double
        Get
            Return CType(Me("AboutWindowTop"),Double)
        End Get
        Set
            Me("AboutWindowTop") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
    Public Property AboutWindowWidth() As Double
        Get
            Return CType(Me("AboutWindowWidth"),Double)
        End Get
        Set
            Me("AboutWindowWidth") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("420")>  _
    Public Property AboutWindowHeight() As Double
        Get
            Return CType(Me("AboutWindowHeight"),Double)
        End Get
        Set
            Me("AboutWindowHeight") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.NextPlayer.MySettings
            Get
                Return Global.NextPlayer.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
