name: Auto-approve PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Auto-approve PR
      uses: hmarr/auto-approve-action@v4
